<a href="https://colab.research.google.com/github/Rogerio-mack/fNIRS/blob/main/A_Carol_create_channel_types_Motor_Parietal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tabela de Canais Motor $\times$ Parietal

Cria Tabela de Canais Motor $\times$ Parietal em .csv.

In [2]:
channel_types_text = """S1_D1 = Hole 1 (D1 - B2) = Motor ; 
S1_D8 = Hole 9 ( D8 - B2)= Motor ; 
S1_D14 = Hole 20 (D6 - B3) = Motor ; 
S2_D2= Hole 2(B2-D2) = Motor ; 
S2_D3= Hole 3 (B2-D3) = Motor ; 
S2_D8= Hole 9 (D8 - D2) = Motor ; 
S2_D9= Hole 13  (D1 - B3) = Motor ; 
S2_D11= Hole 16 (D3 - B3) = Parietal ; 
S3_D4= Hole 4 (D4 - B2) = Parietal ; 
S3_D5= Hole 5 (D5- B2) = Parietal ; 
S3_D9= hole 13 (D1 - B3) = Motor ; 
S3_D10= Hole 14 (D2 - B3) = Parietal ; 
S3_D12= Hole 17 (D4 - B3) = Parietal ; 
S4_D6= Hole 6 ( |D6 - B2) = Parietal ; 
S4_D7= Hole 7 (D7 - B2) = Parietal ; 
S4_D10= Hole 14 (D2 - B3) = Parietal ; 
S4_D13= Hole 19 (D5 - B3) = Parietal ; 
S5_D8= Hole 9 (D8 - B1) = Motor ; 
S5_D11= Hole  16 (D3 - B3) = Parietal ; 
S5_D14= Hole 20 (D6 - B3) = Motor ; 
S5_D15= Hole 21 (D7 - B3) = Motor ; 
S6_D10= Hole 14 (D2 - B3) = Parietal ;
S6_D12= Hole 17 (D4 - B3) = Parietal ; 
S6_D13= Hole 19 (D5 - B3) = Parietal"""

In [3]:
import pandas as pd

channel_SD = pd.DataFrame()
channel_name = []
channel_type = []
channel_hole = []

for ch in channel_types_text.replace(' ','').replace('\n','').split(';'):
  channel_name.append( ch.split('=')[0] )
  channel_type.append( ch.split('=')[2] )
  channel_hole.append( ch.split('=')[1] )

channel_SD['channel_name'] = channel_name
channel_SD['channel_type'] = channel_type
channel_SD['channel_hole'] = channel_hole

channel_SD

   channel_name channel_type   channel_hole
0         S1_D1        Motor   Hole1(D1-B2)
1         S1_D8        Motor   Hole9(D8-B2)
2        S1_D14        Motor  Hole20(D6-B3)
3         S2_D2        Motor   Hole2(B2-D2)
4         S2_D3        Motor   Hole3(B2-D3)
5         S2_D8        Motor   Hole9(D8-D2)
6         S2_D9        Motor  Hole13(D1-B3)
7        S2_D11     Parietal  Hole16(D3-B3)
8         S3_D4     Parietal   Hole4(D4-B2)
9         S3_D5     Parietal   Hole5(D5-B2)
10        S3_D9        Motor  hole13(D1-B3)
11       S3_D10     Parietal  Hole14(D2-B3)
12       S3_D12     Parietal  Hole17(D4-B3)
13        S4_D6     Parietal  Hole6(|D6-B2)
14        S4_D7     Parietal   Hole7(D7-B2)
15       S4_D10     Parietal  Hole14(D2-B3)
16       S4_D13     Parietal  Hole19(D5-B3)
17        S5_D8        Motor   Hole9(D8-B1)
18       S5_D11     Parietal  Hole16(D3-B3)
19       S5_D14        Motor  Hole20(D6-B3)
20       S5_D15        Motor  Hole21(D7-B3)
21       S6_D10     Parietal  Hole14(D2-B3)
22       S6_D12     Parietal  Hole17(D4-B3)
23       S6_D13     Parietal  Hole19(D5-B3)

In [5]:
channel_SD.to_csv('channel_types.csv',index=False)